### ISSUE TITLE
send dfi form bsc to dfichain and my dfi lost 

### ISSUE THREAD

**Issue by zhanglingbin** [muirglacier/bridge-ui#10]
I send 0.5 dfi from bsc to dfichain, I can see this 0.5 dfi on defiscan,  but cant see it in light wallet.

https://bscscan.com/tx/0xce69dbce31fadd1c854b4eaf429643241753f55883dddc1cb5c5c8425240273d

https://defiscan.live/transactions/2b03e445198501620dd4a6969f409bdef4ae2af231fb457c187d7d54e3115ca9

**Comment by zhanglingbin** [comment]
![11111111](https://user-images.githubusercontent.com/32158084/158741708-d9ff663d-290d-405e-9f46-d39443022d28.jpg)

almost 1hour after bridging, still 0.099

**Comment by muirglacier** [comment]
Problem is identified and the fix will be made live in the next 30 minutes. I will let you know once this is the case.
I will also add a recovery function here, so past coins that got stuck can be recovered.

Thank you so much for your contribution. Just let me know your DFI address :-)

**Comment by zhanglingbin** [comment]
> 

Thank for your reply.  My DFI address is df1qcwjza40elp7ue4t24qse5jswkjz5qwj0fgdggw

**Comment by daffilein** [comment]
had the same issue with these transactions: 

https://bscscan.com/tx/0x43244c83639a6d098c6379258afe16974e526a4b194c304cbc0aa80335b5b862 (4.99 DFI)
https://bscscan.com/tx/0x0d97f849538ece82c38a520f2c4da55a86dea24937be1a79bad32ab2e6804de3 (0.49 DFI)

Sent these Bridged DFI from Metmask to my wallet db2MenByVnXF6KTCXZ5GALLt5xhSPJkFUF, which never arrived

This TA worked: https://bscscan.com/tx/0x21f9aae028ad4be3fdd0af17cd2f76815144c983b87b930f84a6108b9d4c07ee (0.5 DFI)

Hope this helps for further analysis and correction.

**Comment by crypnull** [comment]
I have have the same probem... Yet my issue seems to be overlooked? https://github.com/muirglacier/bridge-ui/issues/6
