### ISSUE TITLE
Naming of BSC missleading

### ISSUE THREAD

**Issue by mrgrauel** [muirglacier/bridge-ui#11]
In the UI the BSC is named "Binance Chain" instead of "Binance Smart Chain". I wasn't confused, but friends of mine asked me if it's really the origin chain instead of the Smart Chain.

See https://www.bnbchain.world/en for the Naming of Binance Chain and Binance Smart Chain.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/148758/158740839-e7856bd1-0b43-4c68-a079-86e24a8a7753.png">

**Comment by John-Gee** [comment]
Wasn't BSC renamed to BNB Chain? https://www.yahoo.com/video/binance-smart-chain-rebrands-bnb-091824225.html

**Comment by mrgrauel** [comment]
True it should be "BNB Chain" 🤔

**Comment by mrosberghaus** [comment]
The chains are now called:

- BNB Beacon Chain
- BNB Smart Chain

<img width="204" alt="image" src="https://user-images.githubusercontent.com/148758/159120518-c6ea736a-6ddc-441e-a063-d29fcbf87f58.png">

So the naming should be "BNB Smart Chain" to be accurate.
