### ISSUE TITLE
two question about bridge

### ISSUE THREAD

**Issue by zhanglingbin** [muirglacier/bridge-ui#12]
Just curious， if I dont click the "Submit to Binance Chain" and close the window, what will happen ?
![11111](https://user-images.githubusercontent.com/32158084/158748060-ebe5997c-fa90-4b72-9e0d-dcec78c942bf.jpg)

====================================
And, if I close this window before bridging finished, what will happen ?
![3333](https://user-images.githubusercontent.com/32158084/158748287-1b627a05-dcd5-45dc-b18d-62191f580b7a.jpg)

**Comment by muirglacier** [comment]
Hey, in the first case the coins would be in limbo.
In the second case, you can just enter the same receipient address into the website and it will recover.

I thought about adding a seperate recovery function so in the first case, people who forgot to click the button can recover easily.
Would you maybe have any idea, what you would prefer from a user's point of view?

Thanks for all your contributions so far !!!

**Comment by zhanglingbin** [comment]
> 

for first case, I think your idea is very good. Like https://wormholenetwork.com/, this provides a way to continue the bridging process. Good for you.
