### ISSUE TITLE
Withdrawl dfi form bsc to dfichain and not comming in

### ISSUE THREAD

**Issue by Hynni** [muirglacier/bridge-ui#17]
Hello,
i tried to send my dfi address yesterday afternoon via bridge 123.001 defi on from brdfi and they don't arrive.

The hash ID on the BSC chain is:
0x4dad90042739389df857ed82467e1f938cef8b16c831167eb00156e437da8f0e

My Meta Mask address is:
0x7cee45497ff04a7613d5eb86470a4367087d3bcf

My defi address is:
dRP2Qwgaydr6NiD2dLgruE6BRg1ytuJd89

When I started the process via Metamask I confirmed the transaction, see screenshot.

![Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_48_55](https://user-images.githubusercontent.com/101993740/160279906-c2e94b21-ab31-4a9c-86db-bf82a1e0cc1c.png)

![Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_48_58](https://user-images.githubusercontent.com/101993740/160279888-53d6e3b1-8e23-475c-a23c-964c191402d3.png)

![Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_49_07](https://user-images.githubusercontent.com/101993740/160279923-e109a990-85a0-49db-9aae-8bafe887a5af.png)

![MetaMask Notification 26 03 2022 17_49_23](https://user-images.githubusercontent.com/101993740/160279931-563924f1-2528-4257-90ec-bb72fa4cd7dd.png)

![MetaMask Notification 26 03 2022 17_49_30](https://user-images.githubusercontent.com/101993740/160279938-634c4826-3d60-444d-96b8-6bd3f2ac0c14.png)

After I confirmed the confirmation via Metamask, the confirmation went to 3/5. 

The link to the transaction was displayed and I opened it in a new tab, see screenshot.

![MetaMask Notification 26 03 2022 17_51_21](https://user-images.githubusercontent.com/101993740/160279944-a9476156-d228-4d4b-b11f-70a0bbd7990d.png)

I have not closed the confirmation window from the bridge and have not updated it.

After I went back to the confirmation tab, it was at 1/5 again and stopped completely and nothing happened, see screenshot.

![Binance Transaction Hash (Txhash) Details _ BscScan und 2 weitere Seiten - Persönlich – Microsoft​ Edge 26 03 2022 17_59_24](https://user-images.githubusercontent.com/101993740/160279950-070d84c8-e221-4a9a-a9de-071e53045fa2.png)

However, the hashlink was created on the BSC. However, I have not yet received my defis.

Please check whether my transaction has really gone through via the bridge.

I don't want my defis to be gone now. After all, they were 123.001 DFI.

Many thanks.

BR, Henning

**Comment by muirglacier** [comment]
Hi Henning,

I will send you all those coins plus a bug bounty tomorrow! Problem is known and will also be fixed tomorrow!

Thanks for all your help

Sent from my iPhone

On 27 Mar 2022, at 9:53 pm, Hynni ***@***.***> wrote:

﻿

Hello,
i tried to send my dfi address yesterday afternoon via bridge 123.001 defi on from brdfi and they don't arrive.

The hash ID on the BSC chain is:
0x4dad90042739389df857ed82467e1f938cef8b16c831167eb00156e437da8f0e

My Meta Mask address is:
0x7cee45497ff04a7613d5eb86470a4367087d3bcf

My defi address is:
dRP2Qwgaydr6NiD2dLgruE6BRg1ytuJd89

When I started the process via Metamask I confirmed the transaction, see screenshot.

[Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_48_55]<https://user-images.githubusercontent.com/101993740/160279906-c2e94b21-ab31-4a9c-86db-bf82a1e0cc1c.png>

[Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_48_58]<https://user-images.githubusercontent.com/101993740/160279888-53d6e3b1-8e23-475c-a23c-964c191402d3.png>

[Releasing - Defichain Bridge und 1 weitere Seite - Persönlich – Microsoft​ Edge 26 03 2022 17_49_07]<https://user-images.githubusercontent.com/101993740/160279923-e109a990-85a0-49db-9aae-8bafe887a5af.png>

[MetaMask Notification 26 03 2022 17_49_23]<https://user-images.githubusercontent.com/101993740/160279931-563924f1-2528-4257-90ec-bb72fa4cd7dd.png>

[MetaMask Notification 26 03 2022 17_49_30]<https://user-images.githubusercontent.com/101993740/160279938-634c4826-3d60-444d-96b8-6bd3f2ac0c14.png>

After I confirmed the confirmation via Metamask, the confirmation went to 3/5.

The link to the transaction was displayed and I opened it in a new tab, see screenshot.

[MetaMask Notification 26 03 2022 17_51_21]<https://user-images.githubusercontent.com/101993740/160279944-a9476156-d228-4d4b-b11f-70a0bbd7990d.png>

I have not closed the confirmation window from the bridge and have not updated it.

After I went back to the confirmation tab, it was at 1/5 again and stopped completely and nothing happened, see screenshot.

[Binance Transaction Hash (Txhash) Details _ BscScan und 2 weitere Seiten - Persönlich – Microsoft​ Edge 26 03 2022 17_59_24]<https://user-images.githubusercontent.com/101993740/160279950-070d84c8-e221-4a9a-a9de-071e53045fa2.png>

However, the hashlink was created on the BSC. However, I have not yet received my defis.

Please check whether my transaction has really gone through via the bridge.

I don't want my defis to be gone now. After all, they were 123.001 DFI.

Many thanks.

BR, Henning

**Comment by Hynni** [comment]
Many thanks for your effort.

As soon as the bridge is final, that will be a really big plus for the Defichain :-)

BR, Henning

**Comment by Hynni** [comment]
> Hi Henning, I will send you all those coins plus a bug bounty tomorrow! Problem is known and will also be fixed tomorrow! Thanks for all your help
> […](#)

Hello,
I wanted to ask when I can expect the DFIs :-)

Have a nice weekend. Best regards
Henning

**Comment by Hynni** [comment]
Hi @muirglacier,

when i entered the trx id in this field. I became following error Message:

![image](https://user-images.githubusercontent.com/101993740/167269316-980f1958-a2fa-4013-b6c8-76b9b5364ac0.png)

How do I get my DFI back now?

Thanks very much.

BR, Henning

**Comment by muirglacier** [comment]
Hi, brDFI has been abandoned for the new DFI token when the big update happened. Just sent you the coins from my personal wallet to your defichain address.

Txid: 493b3ba0dc2326d539255a14a7b88c758bffba1fe288f236744f99f354252a05

Thanks for all your input and early testing! You are a legend!

Sent from my iPhone

On 8 May 2022, at 5:42 am, Hynni ***@***.***> wrote:

﻿

Hi @muirglacier<https://github.com/muirglacier>,

when i entered the trx id in this field. I became following error Message:

[image]<https://user-images.githubusercontent.com/101993740/167269316-980f1958-a2fa-4013-b6c8-76b9b5364ac0.png>

How do I get my DFI back now?

Thanks very much.

BR, Henning

**Comment by Hynni** [comment]
Hi @muirglacier,

thank you for allowing me to test the Bridge DFI. 

Especially now that the project is live, it brings a lot of innovation to the Crypto Universion around DeFi now and in the future for the new services.

Thank you very much for sending me the DFIs.

I will now remove the brDFI from the account and insert the new DFI Token.

Thank you again for the great project.

BR Henning
