### ISSUE TITLE
Coins lost / Restore-Deposit Function not working

### ISSUE THREAD

**Issue by razmauser** [muirglacier/bridge-ui#22]
What I did:

- Sent DFI from DFI-Wallet to Bridge-Address
- After 10-Confirmations, the Button "Submit to Binance Chain" did not work (by click there was no action)
- I copied the URL in this step:
[Link of the transaction](https://defichain-bridge.com/#/escape/transaction?createdAt=1649148715308&customParams=%7B%7D&destAddress=0xac75607fa260f350b9f9c8cd16a54e21c2cc2cbe&destChain=binanceSmartChain&expiryTime=1649376000000&gatewayAddress=8Mb5mM2VekBaovnxdSxK1GVGiE3M22Vqhm&id=tx-0xac75607fa260f350b9f9c8cd16a54e21c2cc2cbe-19087000-DFI-BSCC&network=mainnet&nonce=0000000000000000000000000000000000000000000000000000000001233e98&sourceAsset=dfi&sourceChain=defichain&targetAmount=0&transactions=%7B%22decb2f89f891aead5890a81746c2836af1f4446c7cf98945c7fa9c0ff91d694e%3A0%22%3A%7B%22vout%22%3A%7B%22txid%22%3A%22decb2f89f891aead5890a81746c2836af1f4446c7cf98945c7fa9c0ff91d694e%22%2C%22n%22%3A0%2C%22value%22%3A%221.00000000%22%2C%22value_satoshi%22%3A100000000%7D%2C%22current_height%22%3A1769448%2C%22tx_height%22%3A1769448%2C%22confirmations%22%3A0%2C%22good%22%3Afalse%2C%22good_buffer%22%3Afalse%7D%7D&type=mint&userAddress=0xac75607fa260f350b9f9c8cd16a54e21c2cc2cbe)

- Copied the link into a new tap, which offered me a "Resume transcation" screen
- I reconnect my MetaMask Wallet
- Stuck for hours on the "Restoring deposit" screen

![Bildschirmfoto 2022-04-05 um 11 56 40](https://user-images.githubusercontent.com/25085149/161729106-a7b08a57-4f08-4197-8f53-c050e959c860.png)

If I haven't copied the link, how would I be able to get to the restore deposit screen?
When I close my browser and get back to DefiChain bridge, I can connect my MetaMask Wallet. Then I can make a new transaction, but I can*t get to the "Restore Deposit" screen.

My MetaMask Adress: 0xac75607FA260f350B9F9c8Cd16A54e21c2Cc2Cbe
Transaction IDs:
0c3bcda23b202416acd00bdcddeac588af1aafc25e855f9d4ac6e705e80a091f
decb2f89f891aead5890a81746c2836af1f4446c7cf98945c7fa9c0ff91d694e

**Comment by muirglacier** [comment]
Will be sorted within 24 hours and you get double your coins back 🤫

**Comment by razmauser** [comment]
Any news on this. Haven't received anything 'til now.

This is my wallet: df1q3f56hwpauu38rn0mwl3seu4k3gfgnzgufh6m3g

**Comment by muirglacier** [comment]
Please can you retry the recovery function? Should work now
