### ISSUE TITLE
Same problem as others - used DFI bridge and was not able to complete. DFI lost?

### ISSUE THREAD

**Issue by redpill50** [muirglacier/bridge-ui#24]
So, as a test, I sent 3 DFI from my DFI desktop wallet to the DFI bridge and DFI (BSC) were supposed to be deposited in my Metamask. The DFI were sent but nothing happened after I clicked the button to send to BSC chain. No window popped up from Metamask asking for BNB as gas. Tried the Restore method and same result - click the button and no Metamask window.
Here is the Tx ID from my DFI wallet: d5f2ae77e38d6e91456ed8c75089c357e157db6af2545f00aebc66b52f39d986.
Any help would be appreciated.

**Comment by muirglacier** [comment]
Can you let me know the binance chain target address ... or try the recovery function again yourself. We have fixed a couple of things lately.
