### ISSUE TITLE
empty site in metamask and trustwallet, instead of "submit to binancechain"

### ISSUE THREAD

**Issue by mb6767** [muirglacier/bridge-ui#25]
I tried to bridge 10 dfi, 1 dfi and 0.67 dfi.
but after 10 conformations and generating signature, i got an empty site in metamask and trustwallet, instead of "submit to binancechain".
These dfi appear neither in dfi wallet nor in metamask and trust wallet.

**Comment by mb6767** [comment]
this happend on my samsung android smartphone.

**Comment by mb6767** [comment]
please help

**Comment by Stonygan** [comment]
Its a known issue i think, not fixed atm.
https://github.com/muirglacier/bridge-ui/issues/3
