### ISSUE TITLE
Dfi Deposit stuck

### ISSUE THREAD

**Issue by plexi-73** [muirglacier/bridge-ui#28]
Hey there! Used the DefiChain Bridge a couple of times today. But now I have a problem. The Transaction was acutally finished 10/10 but the DFI arent in my Wallet. So I tried to restore with the link. ID: 

02e53ff9bb9eae2f87c002821ca40f1717be1d684db75549d62f847997d92de5

but it does not work. who can help me with this problem? I would be really grateful for that. best regards

**Comment by mootima** [comment]
#26 #27

**Comment by muirglacier** [comment]
Hey, what's your binance chain address? I will have it fixed for you immediately.

We have identified the issue which affected only a small portion of transactions and will have this fixed for future transactions today.

**Comment by plexi-73** [comment]
> Hey, what's your binance chain address? I will have it fixed for you immediately.
> 
> We have identified the issue which affected only a small portion of transactions and will have this fixed for future transactions today.

Thank you very much. My BSC Address is:  0x3871716fE998C0518058899F1cD2345FbDdceaf1

best regards

**Comment by muirglacier** [comment]
Fixed and underlying issue resolved.

https://bscscan.com/tx/0xc10b790631aadcea6cc9dc5fe79e191566bf765fc8ec069e8993ad3506293064

**Comment by plexi-73** [comment]
> Fixed and underlying issue resolved.
> 
> https://bscscan.com/tx/0xc10b790631aadcea6cc9dc5fe79e191566bf765fc8ec069e8993ad3506293064

Many thanks for the quick solution to the problem.

You are a great team!
