### ISSUE TITLE
DFI transaction didn't work

### ISSUE THREAD

**Issue by moonpo** [muirglacier/bridge-ui#29]
I did send few times with the bridge without any issue thanks for that really great tool.
Unfortunately this time it didn't work as expected.

The transaction didn't work here the transaction on the BSC https://bscscan.com/tx/0x41893b29fc2d18bbd9de41e7bbbdfc43310b779a0a713dfc54f1c0add8c00a7a

and here the wallet where it should goes 
dYTCgsgtkYEBhgm2Y4UzhhuKEd1DGsMBwp

I tried the restore function didn't work neither.
Any help will be appreciate.

**Comment by muirglacier** [comment]
Could you please try again now?

Sent from my iPhone

On 18 Jul 2022, at 11:44 pm, moonpo ***@***.***> wrote:

﻿

I did send few times with the bridge without any issue thanks for that really great tool.
Unfortunately this time it didn't work as expected.

The transaction didn't work here the transaction on the BSC https://bscscan.com/tx/0x41893b29fc2d18bbd9de41e7bbbdfc43310b779a0a713dfc54f1c0add8c00a7a

and here the wallet where it should goes
dYTCgsgtkYEBhgm2Y4UzhhuKEd1DGsMBwp

I tried the restore function didn't work neither.
Any help will be appreciate.

**Comment by moonpo** [comment]
Now the transaction can be recover but the DFI aren't in my MetaMask account.
How long should I wait normally to received them?
Here the metamask address 0xa30F76caCCDba3960fC48d6568DC12f0641deCdF

**Comment by muirglacier** [comment]
Shouldn’t be more than a few blocks! I’ll look into this for you

Sent from my iPhone

On 19 Jul 2022, at 12:31 am, moonpo ***@***.***> wrote:

﻿

Now the transaction can be recover but the DFI aren't in my MetaMask account.
How long should I wait normally to received them?

**Comment by moonpo** [comment]
Looks to be working I received my deposit in my account.

Thanks for the support.

**Comment by muirglacier** [comment]
Thanks so much for your reply and glad I could help! You have helped to identify a little problem and it is fixed for all users now! Much appreciated and I wish you a wonderful day

Sent from my iPhone

On 19 Jul 2022, at 12:53 am, moonpo ***@***.***> wrote:

﻿

Looks to be working I received my deposit in my account.

Thanks for the support.
