### ISSUE TITLE
DFI transaction failed  from DFI Wallet to MetaMask Wallet

### ISSUE THREAD

**Issue by rike1706** [muirglacier/bridge-ui#31]

**Comment by Devmenai** [comment]
> I did send few times with the bridge without any issue. So thanks for the great tool. 
> Unfortunately this time it didn't work as expected.
> 
> The transaction didn't work, here the transaction on the BSC network
> 
> https://bscscan.com/tx/0xa469af65d304c54ff81575520f6be3f4f1f33cd72f121be188d37ccc683bc69d
> 
> 
> 
> tried several times: :)
> 
> https://bscscan.com/address/0xeec7b1a5aa5bada82db76a7a79f575a8a585a819
> 
> 
> 
> Brdfi  Adress on the MetaMask Wallet: 0x3961a7B7d2CeB33ad5740624901f6264023C9aC0
> 
> BSC Adress : 0xEEC7B1A5aa5BadA82DB76a7A79f575a8a585A819
> 
> 
> I tried the restore function didn't work neither.
> Any help will be appreciate.

Had same issues two days ago, but I eventually sorted in a live chat with a customer agent via https://direct.lc.chat/14390013/
