### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Sohryu7** [muirglacier/bridge-ui#34]
Hi,

Did the folllowing:
1) Opened the bridge from iPhone > Metamask App > Browser
2) Sent DFI
3) it got to 10 confirmations

4) Page went completely white, no buttons no tx confirmations
waited here for like 20mins

5) reload of the page leads to endless "restoring deposit"

Link
https://defichain-bridge.com/#/escape/transaction?createdAt=1660894026277&customParams=%7B%7D&destAddress=0x229d2e18793de77958cef57a5fdf335ef3c88522&destChain=binanceSmartChain&expiryTime=1661126400000&gatewayAddress=8PZ8pvwr2Rjx4NGeHC6rbsnRZsGddBxKqx&id=tx-0x229d2e18793de77958cef57a5fdf335ef3c88522-19223000-DFI-BSCC&network=mainnet&nonce=00000000000000000000000000000000000000000000000000000000012551d8&sourceAsset=dfi&sourceChain=defichain&targetAmount=0&transactions=%7B%22176cad6f155563ed2bb7b4cb50623c79bfdeba9546f970b2ab00a41dba93bd9f%3A0%22%3A%7B%22vout%22%3A%7B%22txid%22%3A%22176cad6f155563ed2bb7b4cb50623c79bfdeba9546f970b2ab00a41dba93bd9f%22%2C%22n%22%3A0%2C%22value%22%3A%225.00000000%22%2C%22value_satoshi%22%3A500000000%7D%2C%22current_height%22%3A2159925%2C%22tx_height%22%3A2159919%2C%22confirmations%22%3A6%2C%22good%22%3Afalse%2C%22good_buffer%22%3Atrue%7D%7D&type=mint&userAddress=0x229d2e18793de77958cef57a5fdf335ef3c88522

TX
https://defiscan.live/transactions/176cad6f155563ed2bb7b4cb50623c79bfdeba9546f970b2ab00a41dba93bd9f

if you need more info let me know

**Comment by Timo144** [comment]
Hi can you try the recovery?
When this dosent work try it on Desktop /Laptop with the same metamask Adresse
