### ISSUE TITLE
need help please - transaction to my metamask didn´t work

### ISSUE THREAD

**Issue by Evec77** [muirglacier/bridge-ui#35]
Hello!
On August 14th I wanted to bridge some DFI to BSC via the  Defichain-Bridge.
Unfortunately I couldn't get them to my Metamask account. I've been looking for help and a solution to the problem through various channels, so far without success.
The transaction took a while, then I had to recover it on the Defichain-Bridge. Unfortunately Metamask causes problems and a warning appears that the gas cannot be estimated and high fees of around 0.358... BNB are displayed. I've used the bridge a number of times before and it has always worked right, so I don't think I made a mistake. Think it might be a bug.
I am attaching screenshots of the transaction on CakeDeFi (Transaction ID b77e0ff41422e5e0e353a2f5d71c27f94226feaef4283bab10a4323885701bd0) and the metamask window that pops up (my Metamask adr.: 0x5fC5e030B3df2Bdf4d7deb08bd99A5712Fb38166). It would be great if someone could help me. Don't dare to use the bridge anymore.
I would be very grateful for help!
Kind regards Eve.H.
![20220818_222237 (2)](https://user-images.githubusercontent.com/111461031/188309444-78c09de3-8fa1-4901-a6be-fbf8105f751d.jpg)
![20220818_222444 (3)](https://user-images.githubusercontent.com/111461031/188309457-05df46ae-1bf3-4b7f-a531-5b922aaf6ece.jpg)
![20220818_222510 (2)](https://user-images.githubusercontent.com/111461031/188309458-c2f14155-c705-412e-8df0-9f81c31c635f.jpg)
![Screenshot_20220818-221749_Cake DeFi (2)](https://user-images.githubusercontent.com/111461031/188309459-478cce6d-55b9-4956-b033-d47ec629ba57.jpg)

**Comment by muirglacier** [comment]
Looking into it now, will have a solution by tomorrow

Sent from my iPhone

On 4 Sep 2022, at 8:45 pm, Evec77 ***@***.***> wrote:

﻿

Hello!
On August 14th I wanted to bridge some DFI to BSC via the Defichain-Bridge.
Unfortunately I couldn't get them to my Metamask account. I've been looking for help and a solution to the problem through various channels, so far without success.
The transaction took a while, then I had to recover it on the Defichain-Bridge. Unfortunately Metamask causes problems and a warning appears that the gas cannot be estimated and high fees of around 0.358... BNB are displayed. I've used the bridge a number of times before and it has always worked right, so I don't think I made a mistake. Think it might be a bug.
I am attaching screenshots of the transaction on CakeDeFi (Transaction ID b77e0ff41422e5e0e353a2f5d71c27f94226feaef4283bab10a4323885701bd0) and the metamask window that pops up (my Metamask adr.: 0x5fC5e030B3df2Bdf4d7deb08bd99A5712Fb38166). It would be great if someone could help me. Don't dare to use the bridge anymore.
I would be very grateful for help!
Kind regards Eve.H.
[20220818_222237 (2)]<https://user-images.githubusercontent.com/111461031/188309444-78c09de3-8fa1-4901-a6be-fbf8105f751d.jpg>
[20220818_222444 (3)]<https://user-images.githubusercontent.com/111461031/188309457-05df46ae-1bf3-4b7f-a531-5b922aaf6ece.jpg>
[20220818_222510 (2)]<https://user-images.githubusercontent.com/111461031/188309458-c2f14155-c705-412e-8df0-9f81c31c635f.jpg>
[Screenshot_20220818-221749_Cake DeFi (2)]<https://user-images.githubusercontent.com/111461031/188309459-478cce6d-55b9-4956-b033-d47ec629ba57.jpg>

**Comment by Evec77** [comment]
thanks a lot!

**Comment by js-1105** [comment]
Dear Dr. Cagara, I came across the same issue today on 8th, Sep. 2022. The following is my TxID, the UI if the bridge cannot confirm the receival of 1284 DFI already sent. Please help solving the problem, thank you so much in advance:
https://defiscan.live/transactions/9044b34f65e9d743d3e1079f8234eef5b71816deeddffee8904b05476abad9b1

I have used this wonderful bridge not a few times, but it is the first time today I am stuck in this issue.

**Comment by Evec77** [comment]
Dear Dr. Cagara!
Unfortunately, I have not received any further messages so far, so I wanted to ask politely whether You have looked at my problem and can give me any help in this regard? The transaction was not a large sum, but I would still be happy to have the tokens back and if I don't know what the problem was, I don't dare to use the bridge anymore. It is such a great, super useful tool. Thank You in advance for Your reply and assistance.
Best regards Evelyn H.
