### ISSUE TITLE
the bridge cannot confirm the receival of the sent DFI

### ISSUE THREAD

**Issue by js-1105** [muirglacier/bridge-ui#36]
Dear Dr. Cagara, I came across the same issue today on 8th, Sep. 2022 like others that the UI of the bridge cannot confirm the receival of my sent 1284 DFI. The following is my TxID. Please help solving the problem, it is a little bit terrifying. The most important thing is how to get my DFI back into my Metamask wallet. Thank you so much in advance:
https://defiscan.live/transactions/9044b34f65e9d743d3e1079f8234eef5b71816deeddffee8904b05476abad9b1

PS: I have used this wonderful bridge not a few times, but it is the first time today I am stuck in this issue.

**Comment by js-1105** [comment]
I tried to recover the transaction, but failed too
<img width="682" alt="截圖 2022-09-08 上午11 05 55" src="https://user-images.githubusercontent.com/101442789/189025157-e3e15245-02e0-4f9c-9340-2e442ad6aae3.png">

**Comment by muirglacier** [comment]
I am looking into it now, but can you please adding your metamask address into the second field in the recovery?

Sent from my iPhone

On 8 Sep 2022, at 1:08 pm, js-1105 ***@***.***> wrote:

﻿

I tried to recover the transaction, but failed too
[截圖 2022-09-08 上午11 05 55]<https://user-images.githubusercontent.com/101442789/189025157-e3e15245-02e0-4f9c-9340-2e442ad6aae3.png>

**Comment by js-1105** [comment]
How much I thank you for your email. I didn’t add my metamask address because there is no mention of this in the explanation.

Now the issue is solved. Your message is very much appreciated!

One suggestion: Maybe the explanation shall be more clear, and for the second row ,the entering of your address' shall be revised to that of the receiving address, i.e. the metamask or BSC address.  The present one with ERC20 could be misleading.

Thanks again!

Best wishes,
Johannes

PS. How shall I close the case in Github?

muirglacier ***@***.******@***.***>> 於 2022年9月8日 上午11:35 寫道：


I am looking into it now, but can you please adding your metamask address into the second field in the recovery?

Sent from my iPhone

On 8 Sep 2022, at 1:08 pm, js-1105 ***@***.***> wrote:

﻿

I tried to recover the transaction, but failed too
[截圖 2022-09-08 上午11 05 55]<https://user-images.githubusercontent.com/101442789/189025157-e3e15245-02e0-4f9c-9340-2e442ad6aae3.png>

**Comment by muirglacier** [comment]
Hey Johannes,

Thanks for the feedback, I didn’t see how confusing the text was! I will change it today! Thank you so much for the hint

Sent from my iPhone

On 9 Sep 2022, at 1:25 pm, js-1105 ***@***.***> wrote:

﻿

Closed #36<https://github.com/muirglacier/bridge-ui/issues/36> as completed.

**Comment by js-1105** [comment]
you are most welcome! You guys are an excellent team, bringing so much conveniences and new use cases for the community
