### ISSUE TITLE
Could you please help. Lost 2727 dfi by moving to Metamask

### ISSUE THREAD

**Issue by RikPuk** [muirglacier/bridge-ui#37]
Hey,

would be great if you could help me. By moving funds from Defichain to Metamask, the transaction didnt get through. It would be great if you could help me, by solving the problem.

I tried to solve the problem by myself, using 

Transaction Recovery:

Enter your Defichain TxId:
9f9fcb7e4efa0cf2fd0766dda89ca935730586efdb7a9496d54fbe3b58883e6b

Enter ERC20 Target Adress:
0xEEC7B1A5aa5BadA82DB76a7A79f575a8a585A819

but it always want high gas fees. And if I had enough gas fee it didnt went trough either. I
![Screenshot 2022-09-14 184157](https://user-images.githubusercontent.com/93373614/190214712-bd67efec-352e-4ab7-b543-ec6be5f59a33.png)
Thats  al lot of money for me and it would be realy great if you could help me. Thanks a lot and greets!

**Comment by muirglacier** [comment]
Looking into it now, are you sure this is the right transaction? This transaction is from Aug 6, 2022

**Comment by RikPuk** [comment]
Thank you!! Yes, I tried for myself several times, but it didn't worked.

**Comment by muirglacier** [comment]
Try again brother, if not done so yet. If it doesn't work please get back to me
