### ISSUE TITLE
DFI Stuck

### ISSUE THREAD

**Issue by moonpo** [muirglacier/bridge-ui#38]
I did send few times with the bridge without any issue thanks for that really great tool.
Unfortunately this time it didn't work as expected.

The transaction didn't finish properly here the BSC 
https://bscscan.com/tx/0xd39b24f50b7b160fcefef8bab2a8b6a27128f3c67ea68946e8be226e358ca23b

still after 30 minutes no confirmation
![image](https://user-images.githubusercontent.com/12213228/193568887-e0003ae0-b345-4c9f-bc53-afbaba632b33.png)

Recovering the transaction 
![image](https://user-images.githubusercontent.com/12213228/193570441-919381d5-8121-45c1-afa9-944085f65729.png)

Thanks in advance

**Comment by moonpo** [comment]
Thanks I was finally able to recover the transaction 2 days later.
I received my DFI now in my account.

**Comment by muirglacier** [comment]
Awesome, so glad I could help

Sent from my iPhone

On 6 Oct 2022, at 3:45 pm, moonpo ***@***.***> wrote:

﻿

Thanks I was finally able to recover the transaction 2 days later.
I received my DFI now in my account.

**Comment by gittagit123** [comment]
Hello , i have the same Problem. What can i do to recieve the DFI Token ?

**Comment by muirglacier** [comment]
Please try again now lads!
