### ISSUE TITLE
dfi to bnb switch failed.

### ISSUE THREAD

**Issue by MarcBenTobit** [muirglacier/bridge-ui#41]
TxID: 948bdf2595346bd2630a94f2dd90d58a9148ff456fafba39c6ac8d39a6f2c68e
Destination-Adress (BNB) : 0xE04E12cD82CA3601A03483DFe621e698F2b9697e

It was my mistake, no BNB on destination. BNB left, moved BNB to destination-ID, continue, but failed.

Also the restore process ( extimatited fee 0,57 BNB changed to 0,001 BNB ) failed.

Could you pls check? ( 149,7 DFI we are talking abount )

**Comment by Stonygan** [comment]
I see you have received the DFI by now.

https://bscscan.com/tx/0x7a782e2add0bad2780e2b7c03acd1c1b9e81be1efc0919327a02e57d910a8ca3
