### ISSUE TITLE
Missing Dfi Token , with Defichain-Bridge.com

### ISSUE THREAD

**Issue by gittagit123** [muirglacier/bridge-ui#44]
I try to send Dfi with Defichain-bridge.com and lost all my Token.  Can someone help me with Support?

**Comment by Stonygan** [comment]
[#1674](https://github.com/DeFiCh/ain/issues/1674)

**Comment by gittagit123** [comment]
What does it mean ?

**Comment by Stonygan** [comment]
Please provide more details what happened.

**Comment by gittagit123** [comment]
What happened: i send Dfi about the Defichain-bridge.com- after 1 hour waiting , i try to recover the Transaktion. But Error "signatures have invalid lenth/count: 0" -Txid and Adress are right
![20221227_235051](https://user-images.githubusercontent.com/121527063/209775661-4a95d518-ad94-47e8-941b-564de9abd90d.jpg)

**Comment by decentralize7** [comment]
What happened: i've sent dfi token from dfi app to bsc through the defichain bridge

What you expected to happen: i expected to receive the funds from the recipient address

How to reproduce it (as minimally and precisely as possible):
go to defichain bridge site,
put in the bsc recipient adress,
generating dfi receiving adress,
go to the app and send dfi to the dfi receiving adress (defichain-bridge generated adress)

What are your environment parameters:
google chrome

// the frontend is now stucked in loop saying "restoring deposit" - the blockchain tx is confirmed xxx times
please help

**Comment by muirglacier** [comment]
Please try the recovery again now please! If it doesn't work can you please send me your TXID and destination address in a private message (or post it here if you're comfortable with it?)

**Comment by decentralize7** [comment]
> Please try the recovery again now please! If it doesn't work can you please send me your TXID and destination address in a private message (or post it here if you're comfortable with it?)

it worked instantaneous! thanks very much sir
