### ISSUE TITLE
Recovery failed

### ISSUE THREAD

**Issue by ungerst** [muirglacier/bridge-ui#45]
I've send DFI from the LightWallet to the Metamask. The building of the signature doesn't come to the end after 20 Minutes. So i have tried to recover my DFI with the TX-ID and my ER20 Targetaddress. I get the Message: signatures have invalid length/count: 0

So the DFI hangs anywhere between my LightWallet and my Metamask adress. Can you help me and have a look on it.

![1](https://user-images.githubusercontent.com/101056893/210073992-f6624ed9-62c3-49b6-98a2-a3483d380f92.jpg)

**Comment by DeFiChainNFTs** [comment]
Exact same problem for me here.

**Comment by muirglacier** [comment]
Please try the recovery again now please! If it doesn't work can you please send me a private message (or post it publicly here) with the TXID and destination address?
