### ISSUE TITLE
Pull From Defchain sucks, maybe Bridge down for all users

### ISSUE THREAD

**Issue by inka1929** [muirglacier/bridge-ui#46]
Pulling from Defichain no longer works. After the second step, when clicking on 'Confirm' nothing happens. 
Normally the confirmation screen with the 10 fields appears, but this does not appear. It hangs at 'Confirm', see screenshot

the same behavior has been reported by several users

![193755437-96ee274f-18d0-4efa-9037-9d318f6b04c8](https://user-images.githubusercontent.com/121685952/210095766-d7feb0da-a19a-4225-8c32-649c005ccb45.jpg)

**Comment by ungerst** [comment]
Exact behavior. BNB is available on the metamask for the fee. I work with the Chrome browser

**Comment by inka1929** [comment]
ok, works again.
