### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by derstrecker** [muirglacier/bridge-ui#47]
On Chrome and Brave the bridge does not go beyond this point (see attachment). Mac iOS 11.5.1, newest Brave, newest Chrome.
<img width="425" alt="Bildschirmfoto 2023-01-02 um 17 58 14" src="https://user-images.githubusercontent.com/90353867/210261676-001aff62-0967-4fd1-b2b8-6c4882ec739f.png">

**Comment by ungerst** [comment]
Same to me. Windows 11 and newest Chrome.

**Comment by Otti24xx** [comment]
same to me - Windows 10 and newest Chrome and same in newest Edge

**Comment by mindesbunister** [comment]
Same for me on android devices.

**Comment by mastersly** [comment]
same to me ;(

**Comment by muirglacier** [comment]
Please try again now please.
Sorry for the late reply, but there is a dude who constantly harasses me about "updates". Whenever he wants an update I go on a 2 month vacation.

**Comment by GuybrushX** [comment]
> Please try again now please. Sorry for the late reply, but there is a dude who constantly harasses me about "updates". Whenever he wants an update I go on a 2 month vacation.

@muirglacier
It's so easy to start a DoS attack against you? ;-)
