### ISSUE TITLE
Recovery Failure (Pull from Defichain)

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#48]
Recovery is failing. Can you please look into this, to enable recovery of funds?

**Comment by DeFiChainNFTs** [comment]
Same for me here

0f7368e18aba21dbe3a5a940edfd27ac89745510989692932a790c418ead386b

0xD8F28EF3856052504EA38aFce970ea6E29f753cE

**Comment by Defianer** [comment]
My above issue remains unresolved.
Very few times, when opening defichain-bridge.com and clicking through the menu, I get to the point where I see the QR code to send funds, then it switches to "generating signatures" for 2 transactions (probably the two that I mentioned above) and then it's stuck and nothing happens.

Can we have an ETA by when you think you will be able to fix the current issues?

**Comment by Defianer** [comment]
Recovery error message: "signatures have invalid length/count: 0"

**Comment by Defianer** [comment]
All 3 Tx still stuck. Recovery function error message is now:
"TypeError: Failed to fetch"

**Comment by TedT-crypto** [comment]
I have the same issue too!!

**Comment by Defianer** [comment]
Posting the error message from Chrome DevTools Console, as one user commented on Telegram. Does this help for bugfixing?
![image](https://user-images.githubusercontent.com/100243891/211288097-8f39e70e-02d8-43e8-b243-8ea837bc92e6.png)

**Comment by muirglacier** [comment]
Please try the recovery again now please!
