### ISSUE TITLE
No transaction and no recovery

### ISSUE THREAD

**Issue by tkoeddermann** [muirglacier/bridge-ui#50]
Defichain Tx ID:
98f911d3c876bc5c21604edea07983947da9c17ab8e03bf25c13d64f09d2cf71

Transaction stops at the message "generating signatures".
Recovery is failing. Can you please look into this?

**Comment by muirglacier** [comment]
Please try the recovery again now please!

**Comment by tkoeddermann** [comment]
It worked. Thank you.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 16.01.2023, 00:16 schrieb muirglacier ***@***.***>:

   
  Please try the recovery again now please!
