### ISSUE TITLE
3x Tx stuck for 2 weeks; Lost 2510 DFI - From Defichain to BSC (Mint) - Cannot generate signatures, no recovery possible

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#53]
The oldest Tx is now stuck for more than 2 weeks.
If I'm lucky I get to the point where it says "generating signatures". But then it's stuck there and doesn't proceed.
Also the recovery function does NOT work. Error either "signatures have invalid length/count: 0" or "TypeError: Failed to fetch".

I've been able to mint and burn many times before, I know how the UI works. This is not a user error, but a bridge problem.
Please help!

**Comment by muirglacier** [comment]
Please try the recovery again now please!
