### ISSUE TITLE
Bridge UI is down (Pull from Defichain)

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#54]
The UI currently gets stuck for "Pull from Defichain" tx.
It shows "confirming", but the barcode with the target address to send DFI to does not appear.

**Comment by Defianer** [comment]
Please also let me know if I'm eligible for a bug bounty for reporting this.

**Comment by Stonygan** [comment]
It seems you receive the DFI, please reopen when you still have problems.
