### ISSUE TITLE
BSC to DFI Bridge fails since Yesterday 2023-02-18 

### ISSUE THREAD

**Issue by stefan8209** [muirglacier/bridge-ui#59]
Hy Please help me. I ve also the Bridge-Problem.  i transfered some wrappedDFIs from BSC to the Bridge - an error occours... 
When i try to recover with my txID, there comes an error ( TypeError: Load failed)
I tried on several devices... Mac... Iphone  ...

My TX ID on BSC:   0x125f728987f1c1ae561c6afdaeda19832b213c59309aa54390e6439e89c65344

**Comment by Stonygan** [comment]
The bridge is working again, please let us know if problems persist.
