### ISSUE TITLE
BSC to DFI Bridge fails since Yesterday 2023-02-18

### ISSUE THREAD

**Issue by Jan-dfi** [muirglacier/bridge-ui#60]
Hallo,

nachdem ich DFI von der binance chain über die bridge auf mein DFI-light wallet schicken wollten, sind diese noch nicht angekommen

Transaktion1: 50 DFI --> 0xe7adea2db8096dfa19b6f747d08b6a4699f8c20b09982e096474f1116727cd49
Transaktion2: 10 DFI --> 0xf5d75cb7136d4d8ace07b14f320c622a9f39531ece0b2b29418eea14a61484cd

0 of 5 confirmations

**Comment by Stonygan** [comment]
Die Bridge funktioniert wieder, bitte lass uns wissen wenn weiterhin Probleme bestehen.
