### ISSUE TITLE
Send from to Defi Bridge failed, can not complete this transaction

### ISSUE THREAD

**Issue by Hynni** [muirglacier/bridge-ui#61]
Hi,

I have sent defi from my defi address with the 

Transaction ID:
dce136b6f26ce201cd9f906eb04363566efd6bb6128b905367456972cb94db1c

To defi bridge address:
8dkpbNfFiaHPSQGKBLa8dBZS8uqFvYHoGk

sent.

That was 139.42278441 DFI which should be sent to Binance. I sent these over the DefiChain network.

This is the address these should be sent to.
0x7CEE45497fF04A7613D5EB86470A4367087D3Bcf

However, I am unable to complete the transaction.

![image](https://user-images.githubusercontent.com/101993740/219979884-cd408195-82e8-408b-9400-f1287fe5142f.png)

How can the transaction be completed or I got my DFI back.

Thank you very much.

BR, Henning

**Comment by Hynni** [comment]
Hi,

please on Feedback.

Many thanks.

BR, Henning

**Comment by Stonygan** [comment]
Hi, please use the Recovery funtion to receive the DFI on BSC. Below the Button NEXT click on _Click here to recover an incomplete transaction_. Enter your TXID from Defichain and your BSC-Address and then "Recover".
Please close this Issue when it worked for you.
