### ISSUE TITLE
SSL Certficate *.defichain-bridge.com is expired

### ISSUE THREAD

**Issue by ghost** [muirglacier/bridge-ui#62]
SSL Certficate *.defichain-bridge.com is expired

this should be the cause of the current problems

**Comment by mindesbunister** [comment]
thank you for pointing to the problem. Does anyone know when the maintainer of this site is going to do something about it? Is there any way to get in touch with him except via github Issues ?

**Comment by Stonygan** [comment]
Certificate renewed.
