### ISSUE TITLE
Transaction stuck with error "signatures have invalid length/count: 0"

### ISSUE THREAD

**Issue by stn021** [muirglacier/bridge-ui#65]
Hello,

a transaction on defichain-bridge failed.
The error is "signatures have invalid length/count: 0"
I can provide the Defichain TxID and the ERC20 target address, preferrably by private message.

Please let me know what I can do now.

**Comment by Stonygan** [comment]
Please try again and let me know how it works. When you have problems, please write down the TX or contact me in Telegram, when you dont want to share it public.

**Comment by Stonygan** [comment]
Closed as completed.
