### ISSUE TITLE
Tx Stuck, "Send to Defichain", Burn was successful

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#66]
Hi,
my Tx didn't arrive on Defichain despite successful burn.

Recovery function fails with error "TypeError: Failed to fetch".
Please let me know how to proceed to receive my BSC-burned DFI on Defichain.

**Comment by stn021** [comment]
Yes, same here. I wrote my issue a few hours ago.

At first I got the error-message "signatures have invalid length/count: 0"
Now it has changed to "TypeError: Failed to fetch" for the same tx.

Also for a second transaction it is "generating keys" forever.

**Comment by neuriGH** [comment]
Same here, Transaction from BSC to Defichain stucked,  Recover: "TypeError: Failed to fetch"
