### ISSUE TITLE
BSC Burn Tx stuck - Recovery not working

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#68]
BSC Tx 0x344c2bca14f4c1592036689c34d4c4f9e714c57ea0e861b2bbca98d8c82ebf61
(500 DFI)

**Comment by Stonygan** [comment]
Please try again and let me know the result.

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!
