### ISSUE TITLE
Send DFI lower than Miner Fee

### ISSUE THREAD

**Issue by Darkchicken1991** [muirglacier/bridge-ui#7]
I tried the bridge a long time ago and sent a DFI amount that is less than the miner fee. The bridge recognized the transaction. However, the "Submit to Binance Chain" button cannot be pressed. Since then I'm stuck and I can't make new transactions because it recognizes the old transaction every time.

Wallet: df1qlzkr73j6lste02l2fkmr8wq7r9z7324ul05j07

**Comment by Shogoki** [comment]
I can confirm this. the same seems to happen for me. 
I just sent 0.0005 DFI to the bridge address. All goes well, up to the point where i have to click the `Submit to Binance Chain` Button. In the UI it seems, like nothing happens when i click on it.

In the Browser Log i see the following:

```
Submitting via Wallet Provider
MintProcessStep.tsx:347 0x85852282891f6de700096371192684f6f2a69c00 965880a7210443acbd86ce253b285feeeb798f9d5f43c8f10a8fc95946c1f6fc 0 50000 dfi 0xe477ece76481d8157d5a4308f8cc3713b29579d530c48fbbfd8a3c3cedb34959 0x0720c85ba1b6587bb6f8effa55b13919763df3aaed291f76cafe28863e58b518 28
walletHooks.ts:670 0x85852282891f6de700096371192684f6f2a69c00 965880a7210443acbd86ce253b285feeeb798f9d5f43c8f10a8fc95946c1f6fc 0 -950000 DFI 0xe477ece76481d8157d5a4308f8cc3713b29579d530c48fbbfd8a3c3cedb34959 0x0720c85ba1b6587bb6f8effa55b13919763df3aaed291f76cafe28863e58b518 28
```

```
errors.js:76 Uncaught (in promise) Error: invalid number value (arg="amount", coderType="uint256", value=-950000, version=4.0.48)
    at Object.s [as throwError] (errors.js:76:17)
    at e.encode (abi-coder.js:393:20)
    at abi-coder.js:645:59
    at Array.forEach (<anonymous>)
    at B (abi-coder.js:644:12)
    at e.encode (abi-coder.js:804:16)
    at t.encode (abi-coder.js:941:77)
    at t.value (web3-eth-abi.umd.js:43:38)
    at t.value (web3-eth-contract.umd.js:137:49)
    at t.value (web3-eth-contract.umd.js:548:61)
```

Seems like for some reason the amount is set to `-950000`  ?

**Comment by Shogoki** [comment]
okay, i see. it makes kinda sense. as amount is in sats and it is `amount - fee` this results in negative for this low amounts..
Maybe it does make sense to display a message with `minimum amount` at least?
