### ISSUE TITLE
funktioniert die Defichain Bridge? wo kann ich hilfe finden? ...... ich denke sie hat mein Geld verschluckt!

### ISSUE THREAD

**Issue by Bikefire1201** [muirglacier/bridge-ui#70]

**Comment by Bikefire1201** [comment]
Transaktion ID: dc401a411f583636dc562c16822afcd80121386c1a897004c8a564ec71311019
Transaktion ID:  f9b64a39719f8a4ea418c1a535b0844c14a3f32a48370144fe8c908a851dc8e9

**Comment by Stonygan** [comment]
Bitte ein paar mehr Infos, in welche Richtung wurde geswapped? Deine 2. TX-ID ist bereits vom 27. Februar. Auf welcher Adresse wolltest du die Funds erhalten?

**Comment by Stonygan** [comment]
Und wenn noch nicht versucht, bitte die Recoveryfunktion nutzen, der Link dazu steht direkt unter dem Button "NEXT".

**Comment by Bikefire1201** [comment]
Habe es soeben versucht, funktioniert nicht !  ....   Bekomme die Fehlermeldung " This transaction does not pay into your deposit address"
Ich habe die Recoveryfunktion immer versucht !!

Von: Stonygan ***@***.***>
Gesendet: Freitag, 14. April 2023 13:12
An: muirglacier/bridge-ui ***@***.***>
Cc: Bikefire1201 ***@***.***>; Author ***@***.***>
Betreff: Re: [muirglacier/bridge-ui] funktioniert die Defichain Bridge? wo kann ich hilfe finden? ...... ich denke sie hat mein Geld verschluckt! (Issue #70)


Und wenn noch nicht versucht, bitte die Recoveryfunktion nutzen, der Link dazu steht direkt unter dem Button "NEXT".

-

**Comment by Bikefire1201** [comment]
Vorerst danke für die schnelle Antwort
Ich habe von der DefiChain aus versucht zu swappen!
Ich verwende Metamask!
Meine MM Adresse Ist : 0x5BDA4662aDe53b8752f2d1C90616952151a99F09
Defichain Adresse : df1q2rl7xtj5mzttwwr3mtd7vyk3j8hzqw0ashddnn
Die Transaktion ist : dc401a411f583636dc562c16822afcd80121386c1a897004c8a564ec71311019

Die alte Transaktion vom 27, Feb. :
Ich muss ehrlich sagen ich bin mir nicht sicher von welcher Adresse ich Sie swappen wollte: ich habe 2 lightwallet adressen :
df1q2rl7xtj5mzttwwr3mtd7vyk3j8hzqw0ashddnn
und
df1q46pvlhrzvrez6emkc4kqtq707aj7l2eqy5fndk
und beim swappen  immer mit Metamask verbunden (Adresse;  0x5BDA4662aDe53b8752f2d1C90616952151a99F09 )
Transaktion ID : f9b64a39719f8a4ea418c1a535b0844c14a3f32a48370144fe8c908a851dc8e9

Danke
Manfred ( Bikefire )

Von: Stonygan ***@***.***>
Gesendet: Freitag, 14. April 2023 13:08
An: muirglacier/bridge-ui ***@***.***>
Cc: Bikefire1201 ***@***.***>; Author ***@***.***>
Betreff: Re: [muirglacier/bridge-ui] funktioniert die Defichain Bridge? wo kann ich hilfe finden? ...... ich denke sie hat mein Geld verschluckt! (Issue #70)


Bitte ein paar mehr Infos, in welche Richtung wurde geswapped? Deine 2. TX-ID ist bereits vom 27. Februar. Auf welcher Adresse wolltest du die Funds erhalten?

-

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!
