### ISSUE TITLE
Bridge is down (Barcode to deposit is not displayed)

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#71]
For sending to BSC, the UI gets stuck before the barcode and address to deposit are displayed.

**Comment by Defianer** [comment]
Adding error message:

{
	"status": 2,
	"blame": {
		"fail_reason": "there is no shamir-key in the p2p network yet"
	}
}

**Comment by neuriGH** [comment]
Bridge is still down...

**Comment by Stonygan** [comment]
It's in progress

**Comment by Defianer** [comment]
any update what "in progress" means? Do we have an ETA when it should be working again?
It's been a while now and feels like an eternity.

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!
