### ISSUE TITLE
BSC Mint - Stuck Transactions

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#72]
Adding my stuck transaction for sending to/ minting on BSC. Defichain Tx IDs:
5 DFI - 441e4bdca3a7f5a9b9efb6ba97d2dfd30412e49b6e8d132f5551638ec73cdf55
1200 DFI - 29c76882c1745a67856b3050b7173b213a3915a6cdf7f5169af9ccbd069da174
1000 DFI - 85612a4d25f0bb1405e34de49f39c38381a8fe9cd306c68ff2231a458be98d33

Receiving address: 0xfFb4ebfC14c9dF2784fF483629E706E8B49596D1

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!
