### ISSUE TITLE
After Burning on BSC I arrived no DFI

### ISSUE THREAD

**Issue by Bernhardscho** [muirglacier/bridge-ui#73]
Hello,
I used the BSC Bridge from BSC to defichain as usual, but this time I did not receive any DFI in my Wallet. The DFI Burn on BSC was successful.

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!
