### ISSUE TITLE
Bridge not working

### ISSUE THREAD

**Issue by thangdinh123** [muirglacier/bridge-ui#74]
Hi, AD
I have a DFi bridge From DFI network to BSC . but i cant access my token . Please help me get it back
TXID: fcd00b7082794a19cfb4956499ed7a66c674ce960e030381b5ec6f93d86c48b6

**Comment by thangdinh123** [comment]
It's been 2 days and I still haven't received any response from your team. are you still working?

**Comment by thangdinh123** [comment]
Please send me the token back to this wallet address
wallet address: 0xD2a36CdD40D9610B8F30A18FC337FCDc251E7be5

**Comment by muirglacier** [comment]
Funds are safe! And the funniest part comes at the end :-)

The bridge is now stronger than ever.
Over the last three days, we have had a very powerful entity trying to compromise the bridge.

1. The attacker rented dozens of servers from Hetzner and was constantly DDOSing the bridge with 10Gb/s of junk traffic.
2. The attacker somehow managed to get the bridge nodes banned from the Ocean API
3. With the team at MyDefichain we have fought off the attacker, we created an entire new IPTables ruleset to detect such attacks early on and automatically ban the corresponding IP addresses, we introduced rate limiting on all public API nodes, and made a few more parts of the bridge more resilient.
4. From now on the bridge should be more stable than ever
5. In the coming days, I will create and release a new, modern UI that gives users an even better, more streramlined experience!!!
6. Impact on the funds: for some reason we have more than before looool.

All funds are safe, always were, and always will be.
Please try the recovery function again, it should all work now!!

**Comment by thangdinh123** [comment]
I can't restore my bridge command it's crashing like in the picture
TXID: fcd00b7082794a19cfb4956499ed7a66c674ce960e030381b5ec6f93d86c48b6
wallet address: 0xD2a36CdD40D9610B8F30A18FC337FCDc251E7be5
Please help me get my tokens back by direct recovery
