### ISSUE TITLE
Bridge not working, Can't restore the bridge deviation

### ISSUE THREAD

**Issue by thangdinh123** [muirglacier/bridge-ui#77]
I can't restore my bridge command it's crashing 
TXID: fcd00b7082794a19cfb4956499ed7a66c674ce960e030381b5ec6f93d86c48b6
wallet address: 0xD2a36CdD40D9610B8F30A18FC337FCDc251E7be5
Please help me get my tokens back by direct recovery

**Comment by muirglacier** [comment]
working on it right now, its midnight so maybe have patience until tomorrow morning (just a few hours from now). So sorry for the trouble

**Comment by thangdinh123** [comment]
Yes thank you.

**Comment by muirglacier** [comment]
Please try recovery again! It will work 100%.

Sorry again
