### ISSUE TITLE
Recovery not working

### ISSUE THREAD

**Issue by MartinGuth** [muirglacier/bridge-ui#78]
Hi,

my DFI are still stuck since the bridge was down yesterday. I've tried to use the recovery feature, but all I get is a blank white page as soon as I click on "Recover". I've already re-started my browser multiple times and also emptied the cache. Still the same outcome.

Defichain TxID: e8eef50481dfadfcdcd0ce879f2c391ceb6616630759f5faa563eb4d0f4bf315
ERC20 target address: 0xdb7d8bcCC9ee215891f6e53BAFbC70C978fc4870

Could you please help me get to my funds?

Thanks and best,
Martin

**Comment by pappnas** [comment]
Hi,

for me the same. An empty page is displayed with HTTP Status 429 (Too many requests).

Regards,
Marks

**Comment by MartinGuth** [comment]
I've tried it now with Brave Browser, but same outcome.

This is the issue from the Chrome Console:
Acess to fetch at [https://lena.defichain-bridge.com/binance/mint/0xdb7d8bccc9ee215891f6e53bafbc70c978fc4870/e8eef50481dfadfcdcd0ce879f2c391ceb6616630759f5faa563eb4d0f4bf315/0](https://lena.defichain-bridge.com/binance/mint/0xdb7d8bccc9ee215891f6e53bafbc70c978fc4870/e8eef50481dfadfcdcd0ce879f2c391ceb6616630759f5faa563eb4d0f4bf315/0) from origin [https://defichain-bridge.com](https://defichain-bridge.com) has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
