### ISSUE TITLE
Bridge to Defichain: Burned, but not received

### ISSUE THREAD

**Issue by Defianer** [muirglacier/bridge-ui#81]
Hi,
tried to bridge to Defichain.
BSC Burn Tx ID 0xa5681287c4131855f482569e59aed91df1a10e8c78b4ab5b55b1ac3e1ba82257
Defichain Receiving address df1qs7uza0nxz9pq9tuwrh7dmslfkqs63aey7yeghv.

Tokens not received on Defichain. Recovery doesn't work, Error message "could not sign the payout request".
Please help! Thx in advance.

**Comment by Defianer** [comment]
Above Tx could be recovered now - which didn't work previously.

New BSC Burn Tx that is stuck now is 0x56496a467c4044068215212a6b6785c9df652a7dd2bf521cbce97458db846843.
1800 DFI, recovery doesn't work, same error as I had above earlier.

**Comment by Stargazerr1** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Stonygan** [comment]
Is the problem still present? If so, please let us know your DFI address to which the funds should be sent.
