### ISSUE TITLE
DFI received from defichain but mint fails repeatedly

### ISSUE THREAD

**Issue by stn021** [muirglacier/bridge-ui#86]
Hello,

my transaction 19348472d3234473eb6a21327019802b71b9712e0d00a43fcb2e6fc595c083b0
was received on the bridge, but once I press "Mint DFI on Binance Chain" I get an error
'SyntaxError: "undefined" is not valid JSON'

Also it switches to "Maintenance Mode" every few minutes,

Other transactions on the same browser with the same addresses worked fine.
Could you please check?

Thank you, best regards, stn

**Comment by baf999** [comment]
Same problem here

f2a18c28712f37adf377612559713a2968ab75da4ffbbcd157c43c3f9d377aaf
20c48d5b55c7b61f1fa7d2435d59a843c0a35d0a0b52153831ea8e18afe523fc

Both just small amounts but still some error here.

**Comment by baf999** [comment]
Same problem here

**Comment by baf999** [comment]
check

**Comment by the-bastian-fischer** [comment]
Same problem here

f2a18c28712f37adf377612559713a2968ab75da4ffbbcd157c43c3f9d377aaf
20c48d5b55c7b61f1fa7d2435d59a843c0a35d0a0b52153831ea8e18afe523fc

These are just small amounts, still some error.

**Comment by stn021** [comment]
Well, it worked, finally.
