### ISSUE TITLE
Stuck transfer BSC to Defichain

### ISSUE THREAD

**Issue by stn021** [muirglacier/bridge-ui#87]
Hello,

transaction 0xc45e345fb602f875baeadad41dba42f9e4d040ba5e31c519c3b1cfccca2ed77b
(BSC => DefiChain) is stuck.
Recover appears to work at first ("Waiting for your burn to be confirmed on the network:") but 1 minute later it fails "This transaction could not be minted on defichain, please try again in a few minutes."

Same a few minutes later.

Also it switches to "Maintenance Mode" every few minutes,

**Comment by Stonygan** [comment]
Is the problem still present? If so, please let us know your DFI address to which the funds should be sent.

**Comment by stn021** [comment]
Hello, thank you, this issue is solved.
THX, stn

Am Di., 12. Dez. 2023 um 15:31 Uhr schrieb Stonygan <
***@***.***>:
