### ISSUE TITLE
Another transaction is stuck on the bridge

### ISSUE THREAD

**Issue by yannic-m** [muirglacier/bridge-ui#89]
Hello,

transaction 0xbf03fcf608c0ee655d940aad13ee713fda6958749c94fd7a0f9da5c523bab562 , from bsc to defichain is stuck with error-message "cannot be minted on defichain".

I have tried recover multiple times. Either I get the same error or the bridge switches into maintenance mode.
Please check.

THX YM

**Comment by Stonygan** [comment]
Please try recover again.

**Comment by yannic-m** [comment]
Worked, thanks
