### ISSUE TITLE
BSC bridge to MetaMask failed, subsequent restoration attempt looks to have failed (lost or misplaced funds)

### ISSUE THREAD

**Issue by Matt283** [muirglacier/bridge-ui#9]
0.25 DFI successfully bridged.

1.0 DFI, Same method used, after 10 confirmations the submit button was not active. Left for about an hour, pressed back and a timer showed 'restoring deposit', as below:
![image](https://user-images.githubusercontent.com/85042077/158707790-61e6e7b2-ef84-4825-88ef-cc65a9e4b7f7.jpeg)

Continued for some time and failed.
Transaction lost (funds left wallet, no evidence of BscScan txn info) - DeFi scan Tx looks to be: 20ac8c8a697adb52894b10355722094f441a82bbfe53b15715668a83f2560c80

Tried afterwards 0.5 DFI - All good.

**Comment by MacTrady** [comment]
Happened to me too!

06687cee099185e1f2e7e245bcba5ac83e86695ba320ca7e87e660e5dec46ff1


![DFI Bridge 2022-03-17 12-20-46](https://user-images.githubusercontent.com/53078206/158809362-d62ac24b-9c46-4aa5-b0fb-60e0481cf24b.png)

Worked afterwards, but previous transaction is still missing.
Any ideas to recover?

**Comment by Matt283** [comment]
I have been trying to replicate this - without success. So It is good that you could.
I didn't save that error message so it's great you have captured it here.
